### ISSUE TITLE
Drag and Drop option

### ISSUE THREAD

**Issue by TonyYa4AI** [tpartner/LimeSurvey-Image-Interest-Points-4x#1]
It would be awesome to consider a drag and drop option. E.g. to assign attributes to objects. Regarding the given photo there could be snippets like 'tree', 'house', 'street' that should be placed correctly. Greetings

**Comment by tpartner** [comment]
This is not an issue.

**Comment by TonyYa4AI** [comment]
True - sorry, "just" a feature request
